all:
	gcc -std=gnu99 -c main.c
	gcc -std=gnu99 -c admin.c
	gcc -std=gnu99 -c menuc.c
	gcc -std=gnu99 -c tool.c
	gcc -std=gnu99 -c supermanager.c
	gcc -std=gnu99 -c manager.c
	gcc main.o admin.o menuc.o tool.o supermanager.o manager.o -o Stu
